# ─── Stage 1: Build Frontend ──────────────────────────────────
FROM node:20-alpine AS frontend-build

WORKDIR /app

# shared types are aliased as @shared in the frontend
COPY shared/ ./shared/

WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci --no-audit --no-fund

COPY frontend/ .
RUN npm run build


# ─── Stage 2: Build Backend ───────────────────────────────────
FROM node:20-slim AS backend-build

# Prisma's native query engine requires OpenSSL
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app/backend
COPY backend/package*.json ./
# Prisma schema must exist before `npm ci` because postinstall runs `prisma generate`
COPY backend/prisma ./prisma
RUN npm ci --no-audit --no-fund

COPY backend/ .
# TypeScript compile (prisma client already generated by postinstall above)
RUN npx tsc


# ─── Stage 3: Production Image ────────────────────────────────
FROM node:20-slim AS production

# Prisma's native query engine requires OpenSSL at runtime too
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app/backend

COPY --from=backend-build /app/backend/node_modules ./node_modules
COPY --from=backend-build /app/backend/dist ./dist
COPY --from=backend-build /app/backend/package.json ./package.json

# Prisma schema + migrations required at runtime for migrate deploy
COPY backend/prisma ./prisma

# Frontend dist — Express serves this as the SPA
COPY --from=frontend-build /app/frontend/dist /app/frontend/dist

ENV NODE_ENV=production
ENV PORT=3001
EXPOSE 3001

# Run migrations then start the server
CMD ["sh", "-c", "node_modules/.bin/prisma migrate deploy && node dist/index.js"]
