[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node_modules/.bin/prisma migrate deploy 2>&1; node dist/index.js 2>&1"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
